[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["connex/*"]
exclude = [
  ".venv/**",
  ".uv/**",
  ".uv-cache/**",
  ".pytest_cache/**",
  ".ruff_cache/**",
  "**/__pycache__/**",
  ".DS_Store",
]

[project]
name = "connex"
version = "0.4.0"
description = "Fine-grained, dynamic control of neural network topology in JAX."
readme = "README.md"
requires-python =">=3.12"
license = {file = "LICENSE"}
authors = [
  {name = "Leonard Gleyzer"},
]
keywords = ["jax", "neural-networks", "deep-learning"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
]
urls = {repository = "https://github.com/leonard-gleyzer/connex" }
dependencies = [
    "equinox>=0.13.8",
    "jax>=0.10.2",
    "networkx>=3.6.1",
]

[dependency-groups]
dev = [
    "optax>=0.2.6",
    "pytest>=9.0.2",
]

[project.optional-dependencies]
docs = [
  "hippogriffe==0.2.2",
  "griffe==1.7.3",
  "mkdocs==1.6.1",
  "mkdocs-include-exclude-files==0.1.0",
  "mkdocs-material==9.6.7",
  "mkdocstrings==0.28.3",
  "mkdocstrings-python==1.16.8",
  "pymdown-extensions==10.16"
]

[tool.ruff]
line-length = 90
exclude = [".*"]

[tool.ruff.lint]
select = ["E", "F", "I001"]
ignore = ["E402", "E721", "E731", "E741", "F722", "F841"]
fixable = ["I001", "F401"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
order-by-type = false

[tool.ruff.lint.pycodestyle]
max-line-length = 120
